server:
  port: 8781


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: order-service
  redis:
    database: 0
    host: 139.199.122.209
    port: 6379
    timeout: 2000
  zipkin:
    base-url: http://139.199.122.209:9411


feign:
  hystrix:
    enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
