server:
  port: 8781


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: order-service
  redis:
    database: 0
    host: 139.199.122.209
    port: 6379
    timeout: 2000

feign:
  hystrix:
    enabled: true
  client:
    config:
      connectTimeout: 5000
      readTimeout: 5000

hystrix:
  command:
    default:
	  execution:
	    isolation:
	      thread:
	        timeoutInMilliseconds: 5000
